### ISSUE TITLE
Weights

### ISSUE THREAD

**Issue by alexlysenko92** [larsOhne/pvdn#5]
gdrive links for the pretrained weights don't work

**Comment by saralajew** [comment]
Hi @alexlysenko92,

when we tested our package three weeks ago we noticed this issue - excuse the inconveniences. There is already a fix for this but on a private development branch. This branch is not merged yet because it includes new features and updates that are still under review (hopefully it will be merged soon).

Here are the links from the unmerged branch that should work:
[this link for the results presented at IROS 2021](https://drive.google.com/drive/folders/1d1esRWFAElwNN8lqWvr_nec1trPyE1sY?usp=sharing) 
or take [these weights from an unpublished work](https://drive.google.com/drive/folders/14feB0pvcDGX523m_bPMlYWpgKBnQs5pT?usp=sharing) that achieves better performances.
